# config.py — Redirige todo a config_robusto.py (fuente única de verdad)
# No editar aquí: edita config_robusto.py directamente.
from .config_robusto import (
    SALARIO_MINIMO_FILTRO,
    SALARIO_ALERTA_BOGOTA,
    SALARIO_ALERTA_REGIONAL,
    SALARIO_SOSPECHOSO_MAX,
    KEYWORDS_ESTRUCTURACION,
    SECTORES_VALIDOS,
    SECTORES_EXCLUIR_SI_NO_TIENE_KEYWORD,
    TITULOS_OBJETIVO,
    DIAS_MAX_ACTIVO,
    DIAS_MAX_PREMIUM,
    EMPRESAS_DIRECTO,
)

__all__ = [
    "SALARIO_MINIMO_FILTRO",
    "SALARIO_ALERTA_BOGOTA",
    "SALARIO_ALERTA_REGIONAL",
    "SALARIO_SOSPECHOSO_MAX",
    "KEYWORDS_ESTRUCTURACION",
    "SECTORES_VALIDOS",
    "SECTORES_EXCLUIR_SI_NO_TIENE_KEYWORD",
    "TITULOS_OBJETIVO",
    "DIAS_MAX_ACTIVO",
    "DIAS_MAX_PREMIUM",
    "EMPRESAS_DIRECTO",
]
